# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 62414ee5d42f5576a3891dc9431d07d2787a4b670f2ba58bf971047f759ae28325a9b02a6faa457567289c24cfccc2f7a86b32043825704cfa4be4baa63de685

test:
  secret_key_base: 174adf718634b41c63a17ebc3ff711fe897b629215a510a1bb02abbafa3041824e2df654510170fdf43b03902dad356c924683a6aa436a977e7ae3690d424a2e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
